library(shiny)
library(shinyjs)
library(shinyWidgets)
library(shinycssloaders)
library(shinyalert)
#library(shinythemes)
#library(shinydashboard)

library(leaflet)
library(dplyr)
#library(DT)
#library(ggiraph)
library(Hmisc)
library(scales)
library(ggplot2)
library(tools)
library(magicaxis)
library(readxl)
library(miniUI)
library(quantreg)

#library(plotly)

# Read functions
source("R/map_leaflet_code.R")
source("R/ggiraph_plot.R")
