library(shiny)
library(leaflet)
#library(shinythemes)
library(shinydashboard)
library(dplyr)
library(DT)
library(ggiraph)
library(Hmisc)
library(scales)
library(ggplot2)
library(tools)
library(magicaxis)
library(readxl)
#library(shinycssloaders)
library(miniUI)
library(quantreg)
library(shinyjs)
library(shinyWidgets)

# Read functions
source("R/map_leaflet_code.R")
source("R/ggiraph_plot.R")
source("R/comparison_standard_plot.R")
